### ISSUE TITLE
Repository of Examples to Illustrate Quantum Programming Concepts

### ISSUE THREAD

**Issue by simplygreatwork** [quantastica/quantum-circuit#45]
I've been on a mission lately to create lots of [quantum computing examples](https://github.com/simplygreatwork/obvious) in JavaScript. I had been using dabbling with [qcsimulator](http://qcsimulator.github.io/), [qics](https://github.com/adamisntdead/qics/), and [jsqubits](https://github.com/davidbkemp/jsqubits/) but I finally settled on embedding a pared down version of [quantum circuit](https://quantum-circuit.com/).

I'm working with the O'Reilly book ["Programming Quantum Computers"](https://www.oreilly.com/library/view/programming-quantum-computers/9781492039679/), [QASM examples](https://github.com/pnnl/QASMBench), and anything I can comprehend online. These are [some examples](https://github.com/simplygreatwork/obvious) I've created so far which have not been reviewed. I did see this recent [bug report](https://github.com/quantastica/quantum-circuit/issues/44) and I'll need to review whether or not I have hacked around this bug or not. I may eventually re-integrate with the full Quantum Circuit library but this is just what I have so far.

The examples are in my [Github repository](https://github.com/simplygreatwork/obvious).

**Comment by perak** [comment]
@simplygreatwork wow!

Let’s talk privatelly, can you send me a email, which you will find at https://quantastica.com ?

**Comment by perak** [comment]
By the way, following gate matrices were changed this week: `rz`, `crz`, `r2`, `r4`, `r8`. If your code uses any of these gates then it will return different results with version >= 0.9.154

I believe that gate matrices will not change anymore.
