### ISSUE TITLE
Quantum_Classical Export

### ISSUE THREAD

**Issue by CodieKev** [quantastica/quantum-circuit#55]
Quantum Classical export is not working as expected. Whatever you choose for optimizer in exported code you only get the "Powell".
![SharedScreenshot](https://user-images.githubusercontent.com/59618255/93894571-7f930d80-fd0c-11ea-96bf-5c0f9ff84a9d.jpg)
![image](https://user-images.githubusercontent.com/59618255/93894640-95083780-fd0c-11ea-9fc0-56a231e454b6.png)

**Comment by perak** [comment]
@CodieKev Thank you for reporting this bug 👍 

It is fixed now.

**Comment by perak** [comment]
I am closing this issue.

**Comment by CodieKev** [comment]
Respected Petar,
Thank you for solving it and that too this quick.
Regards
Rohit Prasad
