### ISSUE TITLE
Interactive measurements: not clear if possible/how to do

### ISSUE THREAD

**Issue by tobiasBora** [quantastica/quantum-circuit#57]
Hello,

First thanks for this promising package. I'm trying to implement an interactive circuit, in which the user can say in real time the operations to do depending on the previous measurements outcome (NB: it's different from conditional gate as it is really interactive):
- please measure qubit 0.
- The result is 1. What do you want to do?
- Oh, I'd like to see, what happens now if I measure qubit 1 ?
- The result is 1.

I tried to use the `measure` operation to implement a basic measurement of a bell pair (expect 00 or 11 outcome), but does not work as I expect (always 00 outcome, no 11), so I guess I missed something. Is it a bug, or did I missed something?

I saw that there is the measure gate, but I'm affraid by the warning `Measurement gate will reset qubit to measured value only if there are gates with classical control`, as here, I really want to collapse the state after the first measurement, otherwise I'll get inconsistent measurements.

```
<!doctype html>
<html>
  <head>
    <title>Measure bell state </title>
    <meta charset="UTF-8">
  </head>
  <body>
    <script type="text/javascript" src="https://unpkg.com/quantum-circuit"></script> 
    
    <script type="text/javascript">
      for(let i=0; i < 10; i++) { // Repeat the circuit 10 times to see if the probability is the expected one: Pb: only 00 outcome, no 11
          console.log("=== New game: expect sometimes outcome 00, sometimes 11");
          circuit = new QuantumCircuit();
          circuit.addGate("h", -1, [0]);
          circuit.addGate("cx", -1, [0, 1]);
          console.log("Alice will measure")
          console.log(circuit.measure(0))
          console.log("Now bob will measure")
          console.log(circuit.measure(1))
      }
    </script> 
  </body>
</html>
```

**Comment by perak** [comment]
@tobiasBora you need to put circuit.run() before first measurement. addGate realy only adds gate to the circuit, doesn't execute that gate.

**Comment by perak** [comment]
P.S. you can use `measureAllMultishot(shots)` as well:

```
<!doctype html>
<html>
  <head>
    <title>Measure bell state </title>
    <meta charset="UTF-8">
  </head>
  <body>
    <script type="text/javascript" src="https://unpkg.com/quantum-circuit"></script> 
    
    <script type="text/javascript">
          circuit = new QuantumCircuit();
          circuit.addGate("h", -1, [0]);
          circuit.addGate("cx", -1, [0, 1]);
          circuit.run();

          console.log(circuit.measureAllMultishot(10));

    </script> 
  </body>
</html>
```

**Comment by perak** [comment]
One more thing: when you do `measure()` it internally calls `measureAll()` which caches measurement results. Any call to `measure()` after that will give you the same result (if you don't `run()` circuit again. That is actually also how real device behaves - measurement destroys the superposition, any subsequent measurement will return the same result unless you execute the program again.

**Comment by tobiasBora** [comment]
Thanks for your answer, however it does not really solve my need. Indeed, by "adaptive measurements", I mean that I'd like to be able to perform new gates **after** the measurement done by Alice (I really want a real user to say what measurement he want to do, and I can't know the measurement in advance). I tried the following (that just add a X on Bob's qubit), but I get wrong results (like 11 which is supposed to be impossible, the only outcomes behing 01 and 10).

```
<!doctype html>
<html>
  <head>
    <title>Measure bell state </title>
    <meta charset="UTF-8">
  </head>
  <body>
    <script type="text/javascript" src="https://unpkg.com/quantum-circuit"></script> 
    
    <script type="text/javascript">
          circuit = new QuantumCircuit();
          circuit.addGate("h", -1, [0]);
          circuit.addGate("cx", -1, [0, 1]);

      for(let i=0; i < 10; i++) {
          //
          // Run the simulation
          //
          circuit.run();

          console.log("=== New game: expect sometimes outcome 00, sometimes 11");
          console.log("Alice will measure")
          console.log(circuit.measure(0))
          console.log("Now bob will measure")
          // I want to perform operations *after* alice measured her state
          circuit.addGate("x", -1, [1]);
          console.log(circuit.measure(1))
      }
    </script> 
  </body>
</html>
```

**Comment by perak** [comment]
When you add a gate, state is not changed. Remember: `addGate` adds a gate to the circuit but doesn't execute a gate.

You need to do `run()` after modifying circuit (but that will destroy measurement cache).

Let's see... maybe you can do:

```
applyGate(gateName, column, wires, options)` instead `addGate(...)`
```

But that will also reset measurement cache. Maybe the best would be to run circuit with `circuit.run(null, { strictMode: true })` that will destroy superposition after measurement (like real device), and then use applyGate (instead addGate).

P.S. `strictMode: true` is not properly tested, so be careful.

**Comment by perak** [comment]
I just tested - this will not work. Sorry, what you are trying to do is not implemented.

However, why you don't do this:

```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];
creg c[2];
h q[0];
cx q[0], q[1];
measure q[0] -> c[0];
x q[1];
measure q[1] -> c[1];
```

![bell_x](https://user-images.githubusercontent.com/5630814/94973964-66a90a00-050d-11eb-8730-ed6459455864.png)


???

**Comment by tobiasBora** [comment]
Ok, thanks for the answer, too bad it's not implemented. Let me know if there is any plan for that.

And concerning your last proposition I'm not sure to understand, how does it help to apply gates on the fly?

**Comment by tobiasBora** [comment]
Did you close cause it's implemented or not planned?

**Comment by perak** [comment]
@tobiasBora not planned. Sorry.

To me, it doesn't make sense to add gates during execution of the circuit. Quantum computer cannot do that anyway.

Possible alternative is to use classical conditions: gate is executed or not depending on the state of the classical register, which gets state from measurement. That is already implemented.

**Comment by perak** [comment]
Or, possible solution is simply to read state vector, then create new circuit (with the same number of qubits), add gates to that circuit as you wish, initialize it with state vector of previous circuit, and then execute (which is something that you will never be able to do with real quantum hardware anyway, but this would do the job).

**Comment by tobiasBora** [comment]
Ok too bad. I don't see why you say it's impossible to do with a quantum computer, as soon as the coherence time of the quantum system is large enough (i.e. you have a good enough memory) you can just let your system idle and wait to receive instructions to perform the next gate. This is used for instance in the Universal Blind Quantum Computing protocol (itself based on MBQC).

My use case for this was to create a system where a user can, on the go, apply the gates they want to a system. Reproducing the same circuit would not work as there is no guarantee that the previous measurements lead to the same output (probability scales down exponentially with the number of gates). Anyway, I ended up using a different library.
