### ISSUE TITLE
ReferenceError with bundler

### ISSUE THREAD

**Issue by 28Smiles** [quantastica/quantum-circuit#76]
If used with a bundler the stateAsArray function throws an `ReferenceError`. Simple workaround is to insert a `var` to limit the scope. Is this on purpose?

https://github.com/quantastica/quantum-circuit/blob/0a84e31d6b6c1e058e9e28741e156b813e486693/lib/quantum-circuit.js#L12440

**Comment by perak** [comment]
Fixed. @28Smiles thank you for bug report.
