### ISSUE TITLE
Quantum Programming Studio website down

### ISSUE THREAD

**Issue by mirsakhawathossain** [quantastica/quantum-circuit#81]
Maybe Website domain has expired so it doesn't access this platform.

**Comment by perak** [comment]
QPS is online - no issues. Could be some temporary network error.

**Comment by perak** [comment]
@mirsakhawathossain are you able to access it now?

**Comment by mirsakhawathossain** [comment]
Hi there, QPS works perfectly fine. Thank you very much.

**Comment by perak** [comment]
Thank you for reporting issue. Closing now.
