### ISSUE TITLE
Implementation question

### ISSUE THREAD

**Issue by dmvjs** [quantastica/quantum-circuit#89]
https://github.com/quantastica/quantum-circuit/blob/3c526d60dd6fe9f8e0e27a3ceeff081b66b74abc/lib/qasm_import/QASMParser.js#L208

atn deserializer expects a number[] and we pass a string in here, is this intentional?

```ATNDeserializer().deserialize(serializedATN)```

**Comment by perak** [comment]
@dmvjs the code is automatically generated by antlr4, so I guess it is intentional.
